"""Generate ``docs/reference/adr-index.md`` from the records in ``docs/adr/``.

The ADR directory itself is not published (see ADR-0002); this script produces
the small public index that exposes number, title, status, and date.

Run with ``python tools/docs/gen_adr_index.py``. CI regenerates and then runs
``git diff --exit-code`` to catch drift.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

ADR_DIR = Path("docs/adr")
OUT_PATH = Path("docs/reference/adr-index.md")

TITLE_RE = re.compile(r"^#\s+ADR-(?P<number>\d{4}):\s+(?P<title>.+?)\s*$", re.MULTILINE)
FIELD_RE = r"^-\s+\*\*{field}:\*\*\s+(?P<value>.+?)\s*$"


@dataclass(frozen=True)
class Record:
    """A single architecture decision record."""

    number: str
    title: str
    status: str
    date: str
    path: Path


def _field(text: str, field: str) -> str:
    """Extract a MADR bullet field such as ``- **Status:** accepted``."""
    match = re.search(FIELD_RE.format(field=field), text, re.MULTILINE)
    return match.group("value").strip() if match else "unknown"


def parse(path: Path) -> Record | None:
    """Parse one ADR file, or return ``None`` if it is not a numbered record."""
    text = path.read_text(encoding="utf-8")
    title_match = TITLE_RE.search(text)
    if title_match is None:
        return None
    return Record(
        number=title_match.group("number"),
        title=title_match.group("title"),
        status=_field(text, "Status"),
        date=_field(text, "Date"),
        path=path,
    )


def render(records: list[Record]) -> str:
    """Render the index page."""
    lines = [
        "<!-- Generated by tools/docs/gen_adr_index.py. Do not edit by hand. -->",
        "",
        "# Decision records",
        "",
        "Architecture decisions are recorded in `docs/adr/` in the repository.",
        "They are engineering history rather than user documentation, so the",
        "records themselves are not published here; this index lists them.",
        "",
        "| # | Decision | Status | Date |",
        "| --- | --- | --- | --- |",
    ]
    for record in records:
        title = record.title
        if record.status.startswith(("superseded", "deprecated")):
            title = f"~~{title}~~"
        lines.append(
            f"| {record.number} | {title} | `{record.status}` | {record.date} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    """Write the index page and report the number of records found."""
    if not ADR_DIR.is_dir():
        print(f"error: {ADR_DIR} not found", file=sys.stderr)
        return 1
    records = sorted(
        (r for p in ADR_DIR.glob("[0-9][0-9][0-9][0-9]-*.md") if (r := parse(p))),
        key=lambda r: r.number,
    )
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render(records), encoding="utf-8")
    print(f"wrote {OUT_PATH} ({len(records)} records)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
